Issue #133 - Adjust npm scripts to match the template names.

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -7,14 +7,14 @@ if ! npm install > /dev/null 2> /dev/null; then
 fi
 
 echo "Running unit tests..."
-if ! npm run --silent jasmine > /dev/null 2> /dev/null; then
-  echo "!! Running unit tests returned an error! Please run 'npm run jasmine' to see what's wrong."
+if ! npm run --silent test > /dev/null 2> /dev/null; then
+  echo "!! Running unit tests returned an error! Please run 'npm run test' to see what's wrong."
   exit 1
 fi
 
 echo "Running codestyle checks..."
-if ! npm run --silent prettier-check > /dev/null 2> /dev/null; then
-  echo "!! Running codestyle checks returned an error! Please run 'npm run prettier-check' to see what's wrong."
+if ! npm run --silent lint > /dev/null 2> /dev/null; then
+  echo "!! Running codestyle checks returned an error! Please run 'npm run lint' to see what's wrong."
   exit 1
 fi
 
